### PR TITLE
Run benchmarks in Docker against npm, shrinkpack, and Yarn projects

### PR DESCRIPTION
**Pull request by JamieMason**
Hi @siddharthkp,
Thanks a lot for creating this project. I'd understand if you don't take on this pull request but I hoped you might include [shrinkpack](https://github.com/JamieMason/shrinkpack) in these comparisons. 

I started shrinkpack in Feb 2015 to protect against the registry being down, incidents like left-pad etc, and to let you install your npm dependencies without needing internet access. It also makes npm installations faster, but not as fast as Yarn!

Here are some example results from in the Docker container.

```
npm: 15.556s
npm-cached: 11.321s
shrinkpack: 10.857s
shrinkpack-compressed: 11.961s
yarn: 6.413s
```

I've used Docker to make sure the tests aren't affected by whatever npm caches etc I might have on my host machine.

Hope this is useful, thanks for your time.

### CODE REVIEW

**Comment by zkat** [comment]
This is super handy! I'm working on a rewrite of the npm cache over at https://github.com/zkat/cacache so having this might be handy while testing out whether speeds actually improved once I start integrating it. Thanks!

**Comment by siddharthkp** [comment]
@JamieMason this is super cool, I'm up for adding more package managers here

You have added all the cached files as well, is that intentional?

**Comment by JamieMason** [comment]
Sorry for such a slow reply.

> You have added all the cached files as well, is that intentional?

That's intentional yes, all of the benchmark directories except for `/npm` involve installing from an offline cache of tarballs to avoid the network.

Please let me know if there is anything more you'd like me to write up in the repo to explain what is going on. Initially I wasn't sure whether you would want to accept the changes so I left out those things.

Thanks a lot @siddharthkp 

> I'm working on a rewrite of the npm cache over at https://github.com/zkat/cacache so having this might be handy while testing out whether speeds actually improved once I start integrating it

Brilliant, really happy to help, thanks @zkat.

**Comment by JamieMason** [comment]
please let me know if you need anything more from me to finish this @siddharthkp, thanks.

**Comment by zkat** [comment]
@JamieMason How does shrinkpack handle npm5 dependencies? The cache structure has completely changed.

**Comment by JamieMason** [comment]
@zkat yeah it'll need updating to support npm 5, I'll open an issue.

**Pull request merged**
